### ISSUE TITLE
identityToken is null

### ISSUE THREAD

**Issue by FabricioCabeca** [SystangoTechnologies/react-native-apple-authentication#13]
Hi there ! It seems like the login button works, but in the callback the identityToken is never returned, which I need to validate the user server side. The user id and the email are correctly returned.

**Comment by FabricioCabeca** [comment]
Just as a side note, the expo module does return the identityToken, so it is probably not some kind of bad setup on my project.

**Comment by amourya-systango** [comment]
Are you still not able to receive identity token? I'm closing this issue for now. Feel free to open it again if the issue still exists.
