### ISSUE TITLE
Border Radius

### ISSUE THREAD

**Issue by RickameCua** [SystangoTechnologies/react-native-apple-authentication#14]
is it possible to modify the borderRadius?

![Screen Shot 2020-07-13 at 7 50 37 PM](https://user-images.githubusercontent.com/28285289/87301401-1b9cdd80-c542-11ea-99a1-baf6db67baa9.png)
![Screen Shot 2020-07-13 at 7 50 47 PM](https://user-images.githubusercontent.com/28285289/87301405-1d66a100-c542-11ea-9dd1-5be616d914e7.png)

**Comment by amourya-systango** [comment]
Yes with the latest release 1.0.7, you can change title and style of apple login button. You can check props for the same in README file. Closing this issue.
