### ISSUE TITLE
Empty callback After Login

### ISSUE THREAD

**Issue by aryaminus** [SystangoTechnologies/react-native-apple-authentication#3]
Once the Login is done, the returned payload is mostly empty:
```
{"authorizationCode": null, "authorizedScopes": [], "email": null, "firstName": null, "identityToken": null, "lastName": null, "realUserStatus": 1, "state": null, "user": "000466...."}
```

**Comment by akshit5230** [comment]
Found the issue. 
![Screenshot 2019-11-29 at 11 54 31 AM](https://user-images.githubusercontent.com/43376244/69848135-25b5e880-129f-11ea-8f8c-43f72d7f8b42.png)
![Screenshot 2019-11-29 at 11 54 51 AM](https://user-images.githubusercontent.com/43376244/69848136-25b5e880-129f-11ea-91ce-14d505e51438.png)

The object passed from index.js file has key "scopes" and in AppleAuthentication.m file it is parsed as "requestedScopes". Change either and make them same then apple will ask you full name and email to share.

**Comment by aryaminus** [comment]
Tried. Does not work.
![RPReplay_Final1575010306](https://user-images.githubusercontent.com/16350823/69849612-539e2b80-12a5-11ea-93cf-55abe673c36c.gif)

**Comment by alekseiko** [comment]
@aryaminus I had the same issue and it was fixed by removing app from Apple Sign In on my phone.
Just go to _[Settings] -> [Apple ID] -> [Apple ID logins]_ and remove your app from the list.
Apple will request scope again, where you can choose not hide email.

**Comment by alekseiko** [comment]
It happens because It authorise you once and then just send you user ID that means that this user has been authorised before.

**Comment by aryaminus** [comment]
> It happens because It authorise you once and then just send you user ID that means that this user has been authorised before.

Glad to say that this works! Apparently i could have saved quite some time had I read the documentation. Thanks.
