### ISSUE TITLE
How to implement buttonText

### ISSUE THREAD

**Issue by tanz98** [SystangoTechnologies/react-native-apple-authentication#31]
Hello i want to change the text from Sign in with apple to Sign Up with apple, because i get issues from apple review in my register page.

I already try like this but the button was gone : 
```
{SignInWithAppleButton({
	buttonText: "Sign Up With Apple",
	buttonStyle: styles.appleBtn,
	callBack: this.appleSignIn,
})}
```

please help my deadline was 4 days again for up to app store :(

**Comment by tanz98** [comment]
any update :) ?

**Comment by amourya-systango** [comment]
Hello @tanz98,
Please install latest version of this lib 2.0.0 . We have fixed button text issue. Merged the following PR for the same:
https://github.com/SystangoTechnologies/react-native-apple-authentication/pull/32/
