### ISSUE TITLE
Got Error: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1000 "(null)"

### ISSUE THREAD

**Issue by pankajatocdlab** [SystangoTechnologies/react-native-apple-authentication#4]
Got **Error: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1000 "(null)"** when try to login with Apple ID. I have added **Sign In with Apple** capability in my project already.

I have checked on simulator and on real device and got same issue on both and also tested the production build but got same issue.

**Comment by zhekix** [comment]
> Got **Error: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1000 "(null)"** when try to login with Apple ID. I have added **Sign In with Apple** capability in my project already.

@pankajatocdlab, solved a problem?

**Comment by vevnkataSukumar** [comment]
Got Error: Error Domain=com.apple.AuthenticationServices.AuthorizationError Code=1000 "(null)" when try to login with Apple ID. I have added Sign In with Apple capability in my project already.

**Comment by vevnkataSukumar** [comment]
Can any one help to fix this issue.

**Comment by amourya-systango** [comment]
@pankajatocdlab and @vevnkataSukumar, could you guys please check your XCode's Capabilities section for the project in which you are integrating this lib and let me know if Sign in with Apple has enabled or not?

`Sign in with Apple` capability should be enabled.

**Comment by amourya-systango** [comment]
Closing this issue for now. Feel free to open if it is still coming with 2FA enabled accounts.
