### ISSUE TITLE
Scopes not working 

### ISSUE THREAD

**Issue by jacksonej** [SystangoTechnologies/react-native-apple-authentication#6]
FullName and Email is scope is not working

React native version 0.61.2

**Comment by arunkmoury** [comment]
Same here with 0.61.2 & 0.57.8

**Comment by jacksonej** [comment]
I hard coded the permissions in Appleauthentication Xcode project. then it started working. looks like scopes are not getting in Apple native

**Comment by vonrussel** [comment]
Change `scopes` to `requestedScopes` here:
https://github.com/SystangoTechnologies/react-native-apple-authentication/blob/master/index.js#L13

**Comment by Estebank94** [comment]
> Change `scopes` to `requestedScopes` here:
> https://github.com/SystangoTechnologies/react-native-apple-authentication/blob/master/index.js#L13

I tried that but it still isn't working

**Comment by iamgerardm** [comment]
So a couple things here... `requestedScopes` does fix the issue of it asking for name and email during sign in. However, due to Apple policies this information is only returned the very first time it's asked for. After that the user would have to revoke the sign in permissions in Settings > [NAME] > Passwords & Security > Apps Using Your Apple ID

This worked for email, however I also had to change the code in `AppleAuthentication.m` around line 77. 

`NSDictionary* user = @{
                         @"firstName": RCTNullIfNil(credential.fullName.givenName),
												 @"lastName": RCTNullIfNil(credential.fullName.familyName),
                         @"email": RCTNullIfNil(credential.email),
                         @"user": credential.user,
                         @"authorizedScopes": credential.authorizedScopes,
                         @"realUserStatus": @(credential.realUserStatus),
                         @"state": RCTNullIfNil(credential.state),
                         @"authorizationCode": RCTNullIfNil(credential.authorizationCode),
                         @"identityToken": RCTNullIfNil(credential.identityToken)
                         };`

I changed fullName to firstName and lastName as just .fullName does not return anything.

**Comment by amourya-systango** [comment]
@vonrussel @Estebank94  Thanks, I have replaced scopes with requestedScopes and it worked. 
@iamgerardm I am getting Fullname after this, please take the latest code and check if it's working now or not.

**Comment by amourya-systango** [comment]
> Change `scopes` to `requestedScopes` here:
> https://github.com/SystangoTechnologies/react-native-apple-authentication/blob/master/index.js#L13

**Comment by amourya-systango** [comment]
> Change `scopes` to `requestedScopes` here:
> https://github.com/SystangoTechnologies/react-native-apple-authentication/blob/master/index.js#L13

@vonrussel Thanks, I have replaced scopes with requestedScopes and it worked.

**Comment by amourya-systango** [comment]
> > Change `scopes` to `requestedScopes` here:
> > https://github.com/SystangoTechnologies/react-native-apple-authentication/blob/master/index.js#L13
> 
> I tried that but it still isn't working
@Estebank94 Thanks, I have replaced scopes with requestedScopes and it worked.

**Comment by amourya-systango** [comment]
@iamgerardm I am getting Fullname after this, please take the latest code and check if it's working now or not.

**Comment by amourya-systango** [comment]
No activities. Closing this issue for now

**Comment by ImHamzaAnwer** [comment]
still receiving null in fullName
