### ISSUE TITLE
RNSignInWithAppleButton was not found in UIManager.

### ISSUE THREAD

**Issue by vevnkataSukumar** [SystangoTechnologies/react-native-apple-authentication#7]

**Comment by tiffanym19** [comment]
im also encountering this issue

**Comment by amourya-systango** [comment]
@vevnkataSukumar @tiffanym19  Can you guys please let me know which xcode version and OS version you are using? I believe this is something related to configuration, I am using 
Xcode: 11.0 beta 6 (11M392q)
OS: macOS Mojave( 10.14.6)

**Comment by amourya-systango** [comment]
Actually apple signing can only work with XCode 11.x and iOS 13.x. For now, I'm closing this issue.

**Comment by xoapit** [comment]
I am using XCode 11.1, iOS 13.3 but still meet this issue.
