### ISSUE TITLE
apple login return null data

### ISSUE THREAD

**Issue by arjundalal** [SystangoTechnologies/react-native-apple-authentication#8]
when we do apple login it return null object. Please help me to resolve this issues.
Result:
{"authorizationCode": null, "authorizedScopes": [], "email": null, "fullName": null, "identityToken": null, "realUserStatus": 1, "state": null, "user": "001810.9b25b516428f41a5920c6b46b6697674.1051"}
how we get email,fullName in this mehtod.

**Comment by amourya-systango** [comment]
@arjundalal 
This is default behavior, user info is only sent in the ASAuthorizationAppleIDCredential upon initial user sign up. Subsequent logins to your app using Sign In with Apple with the same account do not share any user info and will only return a user identifier in the ASAuthorizationAppleIDCredential. It is recommened that you securely cache the initial ASAuthorizationAppleIDCredential containing the user info until you can validate that an account has successfully been created on your server.
Please visit this link

**Comment by amourya-systango** [comment]
I'm closing this issue for now. If anyone is getting this issue again then feel free to create a new one.
